package com.comstar.mars.entity;

public class Branch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.ID_PARENT
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private Integer idParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.CODE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.PROVINCE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.CITY
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.ADDRESS
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.TELEPHONE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.FAX_NUMBER
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String faxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_BRANCH.CONTACT_PERSON
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String contactPerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.ID
     *
     * @return the value of SYS_BRANCH.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.ID
     *
     * @param id the value for SYS_BRANCH.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.ID_PARENT
     *
     * @return the value of SYS_BRANCH.ID_PARENT
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public Integer getIdParent() {
        return idParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.ID_PARENT
     *
     * @param idParent the value for SYS_BRANCH.ID_PARENT
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setIdParent(Integer idParent) {
        this.idParent = idParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.CODE
     *
     * @return the value of SYS_BRANCH.CODE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.CODE
     *
     * @param code the value for SYS_BRANCH.CODE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.NAME
     *
     * @return the value of SYS_BRANCH.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.NAME
     *
     * @param name the value for SYS_BRANCH.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.PROVINCE
     *
     * @return the value of SYS_BRANCH.PROVINCE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.PROVINCE
     *
     * @param province the value for SYS_BRANCH.PROVINCE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.CITY
     *
     * @return the value of SYS_BRANCH.CITY
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.CITY
     *
     * @param city the value for SYS_BRANCH.CITY
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.ADDRESS
     *
     * @return the value of SYS_BRANCH.ADDRESS
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.ADDRESS
     *
     * @param address the value for SYS_BRANCH.ADDRESS
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.TELEPHONE
     *
     * @return the value of SYS_BRANCH.TELEPHONE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.TELEPHONE
     *
     * @param telephone the value for SYS_BRANCH.TELEPHONE
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.FAX_NUMBER
     *
     * @return the value of SYS_BRANCH.FAX_NUMBER
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.FAX_NUMBER
     *
     * @param faxNumber the value for SYS_BRANCH.FAX_NUMBER
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber == null ? null : faxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_BRANCH.CONTACT_PERSON
     *
     * @return the value of SYS_BRANCH.CONTACT_PERSON
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_BRANCH.CONTACT_PERSON
     *
     * @param contactPerson the value for SYS_BRANCH.CONTACT_PERSON
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }
}