package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DealSecurity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.DEAL_SECURITY_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Long dealSecurityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.PREV_SECURITY_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Long prevSecurityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Integer branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Integer financialProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.STATUS
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private String securityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.TRADE_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Integer tradeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.VALUE_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Integer valueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.NOMINAL
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private BigDecimal nominal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.CLEAR_PRICE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private BigDecimal clearPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.DIRTY_PRICE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private BigDecimal dirtyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.INTEREST
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.SETTLE_AMOUNT
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private BigDecimal settleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.SETTLE_TYPE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private String settleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.YIELD
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private BigDecimal yield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.DIRECTION
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.COUNTERPARTY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private String counterparty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.MODIFY_USER
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private Integer modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY.NOTE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.DEAL_SECURITY_ID
     *
     * @return the value of DEAL_SECURITY.DEAL_SECURITY_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Long getDealSecurityId() {
        return dealSecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.DEAL_SECURITY_ID
     *
     * @param dealSecurityId the value for DEAL_SECURITY.DEAL_SECURITY_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setDealSecurityId(Long dealSecurityId) {
        this.dealSecurityId = dealSecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.PREV_SECURITY_ID
     *
     * @return the value of DEAL_SECURITY.PREV_SECURITY_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Long getPrevSecurityId() {
        return prevSecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.PREV_SECURITY_ID
     *
     * @param prevSecurityId the value for DEAL_SECURITY.PREV_SECURITY_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setPrevSecurityId(Long prevSecurityId) {
        this.prevSecurityId = prevSecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.BRANCH_ID
     *
     * @return the value of DEAL_SECURITY.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.BRANCH_ID
     *
     * @param branchId the value for DEAL_SECURITY.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.FINANCIAL_PRODUCT_ID
     *
     * @return the value of DEAL_SECURITY.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Integer getFinancialProductId() {
        return financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.FINANCIAL_PRODUCT_ID
     *
     * @param financialProductId the value for DEAL_SECURITY.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setFinancialProductId(Integer financialProductId) {
        this.financialProductId = financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.STATUS
     *
     * @return the value of DEAL_SECURITY.STATUS
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.STATUS
     *
     * @param status the value for DEAL_SECURITY.STATUS
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.SECURITY_CODE
     *
     * @return the value of DEAL_SECURITY.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.SECURITY_CODE
     *
     * @param securityCode the value for DEAL_SECURITY.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode == null ? null : securityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.TRADE_DATE
     *
     * @return the value of DEAL_SECURITY.TRADE_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Integer getTradeDate() {
        return tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.TRADE_DATE
     *
     * @param tradeDate the value for DEAL_SECURITY.TRADE_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setTradeDate(Integer tradeDate) {
        this.tradeDate = tradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.VALUE_DATE
     *
     * @return the value of DEAL_SECURITY.VALUE_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Integer getValueDate() {
        return valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.VALUE_DATE
     *
     * @param valueDate the value for DEAL_SECURITY.VALUE_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setValueDate(Integer valueDate) {
        this.valueDate = valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.NOMINAL
     *
     * @return the value of DEAL_SECURITY.NOMINAL
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public BigDecimal getNominal() {
        return nominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.NOMINAL
     *
     * @param nominal the value for DEAL_SECURITY.NOMINAL
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setNominal(BigDecimal nominal) {
        this.nominal = nominal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.CLEAR_PRICE
     *
     * @return the value of DEAL_SECURITY.CLEAR_PRICE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public BigDecimal getClearPrice() {
        return clearPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.CLEAR_PRICE
     *
     * @param clearPrice the value for DEAL_SECURITY.CLEAR_PRICE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setClearPrice(BigDecimal clearPrice) {
        this.clearPrice = clearPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.DIRTY_PRICE
     *
     * @return the value of DEAL_SECURITY.DIRTY_PRICE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public BigDecimal getDirtyPrice() {
        return dirtyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.DIRTY_PRICE
     *
     * @param dirtyPrice the value for DEAL_SECURITY.DIRTY_PRICE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setDirtyPrice(BigDecimal dirtyPrice) {
        this.dirtyPrice = dirtyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.INTEREST
     *
     * @return the value of DEAL_SECURITY.INTEREST
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.INTEREST
     *
     * @param interest the value for DEAL_SECURITY.INTEREST
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.SETTLE_AMOUNT
     *
     * @return the value of DEAL_SECURITY.SETTLE_AMOUNT
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public BigDecimal getSettleAmount() {
        return settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.SETTLE_AMOUNT
     *
     * @param settleAmount the value for DEAL_SECURITY.SETTLE_AMOUNT
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setSettleAmount(BigDecimal settleAmount) {
        this.settleAmount = settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.SETTLE_TYPE
     *
     * @return the value of DEAL_SECURITY.SETTLE_TYPE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getSettleType() {
        return settleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.SETTLE_TYPE
     *
     * @param settleType the value for DEAL_SECURITY.SETTLE_TYPE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setSettleType(String settleType) {
        this.settleType = settleType == null ? null : settleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.YIELD
     *
     * @return the value of DEAL_SECURITY.YIELD
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public BigDecimal getYield() {
        return yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.YIELD
     *
     * @param yield the value for DEAL_SECURITY.YIELD
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setYield(BigDecimal yield) {
        this.yield = yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.DIRECTION
     *
     * @return the value of DEAL_SECURITY.DIRECTION
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.DIRECTION
     *
     * @param direction the value for DEAL_SECURITY.DIRECTION
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.COUNTERPARTY
     *
     * @return the value of DEAL_SECURITY.COUNTERPARTY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getCounterparty() {
        return counterparty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.COUNTERPARTY
     *
     * @param counterparty the value for DEAL_SECURITY.COUNTERPARTY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setCounterparty(String counterparty) {
        this.counterparty = counterparty == null ? null : counterparty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.MODIFY_DATE
     *
     * @return the value of DEAL_SECURITY.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.MODIFY_DATE
     *
     * @param modifyDate the value for DEAL_SECURITY.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.MODIFY_USER
     *
     * @return the value of DEAL_SECURITY.MODIFY_USER
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.MODIFY_USER
     *
     * @param modifyUser the value for DEAL_SECURITY.MODIFY_USER
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY.NOTE
     *
     * @return the value of DEAL_SECURITY.NOTE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY.NOTE
     *
     * @param note the value for DEAL_SECURITY.NOTE
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}