package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DealSecurityAccrue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.DEAL_SECURITY_ACCRUE_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private Long dealSecurityAccrueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private Integer branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private Integer financialProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.STATUS
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private String securityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.ACCRUE_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private Integer accrueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_ACCRUE.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.DEAL_SECURITY_ACCRUE_ID
     *
     * @return the value of DEAL_SECURITY_ACCRUE.DEAL_SECURITY_ACCRUE_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public Long getDealSecurityAccrueId() {
        return dealSecurityAccrueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.DEAL_SECURITY_ACCRUE_ID
     *
     * @param dealSecurityAccrueId the value for DEAL_SECURITY_ACCRUE.DEAL_SECURITY_ACCRUE_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setDealSecurityAccrueId(Long dealSecurityAccrueId) {
        this.dealSecurityAccrueId = dealSecurityAccrueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.BRANCH_ID
     *
     * @return the value of DEAL_SECURITY_ACCRUE.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.BRANCH_ID
     *
     * @param branchId the value for DEAL_SECURITY_ACCRUE.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.FINANCIAL_PRODUCT_ID
     *
     * @return the value of DEAL_SECURITY_ACCRUE.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public Integer getFinancialProductId() {
        return financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.FINANCIAL_PRODUCT_ID
     *
     * @param financialProductId the value for DEAL_SECURITY_ACCRUE.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setFinancialProductId(Integer financialProductId) {
        this.financialProductId = financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.STATUS
     *
     * @return the value of DEAL_SECURITY_ACCRUE.STATUS
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.STATUS
     *
     * @param status the value for DEAL_SECURITY_ACCRUE.STATUS
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.SECURITY_CODE
     *
     * @return the value of DEAL_SECURITY_ACCRUE.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.SECURITY_CODE
     *
     * @param securityCode the value for DEAL_SECURITY_ACCRUE.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode == null ? null : securityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.ACCRUE_DATE
     *
     * @return the value of DEAL_SECURITY_ACCRUE.ACCRUE_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public Integer getAccrueDate() {
        return accrueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.ACCRUE_DATE
     *
     * @param accrueDate the value for DEAL_SECURITY_ACCRUE.ACCRUE_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setAccrueDate(Integer accrueDate) {
        this.accrueDate = accrueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.AMOUNT
     *
     * @return the value of DEAL_SECURITY_ACCRUE.AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.AMOUNT
     *
     * @param amount the value for DEAL_SECURITY_ACCRUE.AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_ACCRUE.MODIFY_DATE
     *
     * @return the value of DEAL_SECURITY_ACCRUE.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_ACCRUE.MODIFY_DATE
     *
     * @param modifyDate the value for DEAL_SECURITY_ACCRUE.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}