package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DealSecurityReceivable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.DEAL_SECURITY_RECEIVABLE_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private Long dealSecurityReceivableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private Integer branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private Integer financialProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.STATUS
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private String securityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.RECEIVE_DATE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private Integer receiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.RECEIVE_TYPE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private String receiveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEAL_SECURITY_RECEIVABLE.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.DEAL_SECURITY_RECEIVABLE_ID
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.DEAL_SECURITY_RECEIVABLE_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public Long getDealSecurityReceivableId() {
        return dealSecurityReceivableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.DEAL_SECURITY_RECEIVABLE_ID
     *
     * @param dealSecurityReceivableId the value for DEAL_SECURITY_RECEIVABLE.DEAL_SECURITY_RECEIVABLE_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setDealSecurityReceivableId(Long dealSecurityReceivableId) {
        this.dealSecurityReceivableId = dealSecurityReceivableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.BRANCH_ID
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.BRANCH_ID
     *
     * @param branchId the value for DEAL_SECURITY_RECEIVABLE.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.FINANCIAL_PRODUCT_ID
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public Integer getFinancialProductId() {
        return financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.FINANCIAL_PRODUCT_ID
     *
     * @param financialProductId the value for DEAL_SECURITY_RECEIVABLE.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setFinancialProductId(Integer financialProductId) {
        this.financialProductId = financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.STATUS
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.STATUS
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.STATUS
     *
     * @param status the value for DEAL_SECURITY_RECEIVABLE.STATUS
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.SECURITY_CODE
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.SECURITY_CODE
     *
     * @param securityCode the value for DEAL_SECURITY_RECEIVABLE.SECURITY_CODE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode == null ? null : securityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.RECEIVE_DATE
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.RECEIVE_DATE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public Integer getReceiveDate() {
        return receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.RECEIVE_DATE
     *
     * @param receiveDate the value for DEAL_SECURITY_RECEIVABLE.RECEIVE_DATE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setReceiveDate(Integer receiveDate) {
        this.receiveDate = receiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.RECEIVE_TYPE
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.RECEIVE_TYPE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public String getReceiveType() {
        return receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.RECEIVE_TYPE
     *
     * @param receiveType the value for DEAL_SECURITY_RECEIVABLE.RECEIVE_TYPE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setReceiveType(String receiveType) {
        this.receiveType = receiveType == null ? null : receiveType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.AMOUNT
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.AMOUNT
     *
     * @param amount the value for DEAL_SECURITY_RECEIVABLE.AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEAL_SECURITY_RECEIVABLE.MODIFY_DATE
     *
     * @return the value of DEAL_SECURITY_RECEIVABLE.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEAL_SECURITY_RECEIVABLE.MODIFY_DATE
     *
     * @param modifyDate the value for DEAL_SECURITY_RECEIVABLE.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}