package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DealSecurityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public DealSecurityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealSecurityIdIsNull() {
            addCriterion("DEAL_SECURITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdIsNotNull() {
            addCriterion("DEAL_SECURITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdEqualTo(Long value) {
            addCriterion("DEAL_SECURITY_ID =", value, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdNotEqualTo(Long value) {
            addCriterion("DEAL_SECURITY_ID <>", value, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdGreaterThan(Long value) {
            addCriterion("DEAL_SECURITY_ID >", value, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEAL_SECURITY_ID >=", value, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdLessThan(Long value) {
            addCriterion("DEAL_SECURITY_ID <", value, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdLessThanOrEqualTo(Long value) {
            addCriterion("DEAL_SECURITY_ID <=", value, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdIn(List<Long> values) {
            addCriterion("DEAL_SECURITY_ID in", values, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdNotIn(List<Long> values) {
            addCriterion("DEAL_SECURITY_ID not in", values, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdBetween(Long value1, Long value2) {
            addCriterion("DEAL_SECURITY_ID between", value1, value2, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andDealSecurityIdNotBetween(Long value1, Long value2) {
            addCriterion("DEAL_SECURITY_ID not between", value1, value2, "dealSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdIsNull() {
            addCriterion("PREV_SECURITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdIsNotNull() {
            addCriterion("PREV_SECURITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdEqualTo(Long value) {
            addCriterion("PREV_SECURITY_ID =", value, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdNotEqualTo(Long value) {
            addCriterion("PREV_SECURITY_ID <>", value, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdGreaterThan(Long value) {
            addCriterion("PREV_SECURITY_ID >", value, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PREV_SECURITY_ID >=", value, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdLessThan(Long value) {
            addCriterion("PREV_SECURITY_ID <", value, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdLessThanOrEqualTo(Long value) {
            addCriterion("PREV_SECURITY_ID <=", value, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdIn(List<Long> values) {
            addCriterion("PREV_SECURITY_ID in", values, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdNotIn(List<Long> values) {
            addCriterion("PREV_SECURITY_ID not in", values, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdBetween(Long value1, Long value2) {
            addCriterion("PREV_SECURITY_ID between", value1, value2, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andPrevSecurityIdNotBetween(Long value1, Long value2) {
            addCriterion("PREV_SECURITY_ID not between", value1, value2, "prevSecurityId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNull() {
            addCriterion("BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNotNull() {
            addCriterion("BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchIdEqualTo(Integer value) {
            addCriterion("BRANCH_ID =", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotEqualTo(Integer value) {
            addCriterion("BRANCH_ID <>", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThan(Integer value) {
            addCriterion("BRANCH_ID >", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BRANCH_ID >=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThan(Integer value) {
            addCriterion("BRANCH_ID <", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThanOrEqualTo(Integer value) {
            addCriterion("BRANCH_ID <=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIn(List<Integer> values) {
            addCriterion("BRANCH_ID in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotIn(List<Integer> values) {
            addCriterion("BRANCH_ID not in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdBetween(Integer value1, Integer value2) {
            addCriterion("BRANCH_ID between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BRANCH_ID not between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIsNull() {
            addCriterion("FINANCIAL_PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIsNotNull() {
            addCriterion("FINANCIAL_PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID =", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID <>", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdGreaterThan(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID >", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID >=", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLessThan(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID <", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID <=", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIn(List<Integer> values) {
            addCriterion("FINANCIAL_PRODUCT_ID in", values, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotIn(List<Integer> values) {
            addCriterion("FINANCIAL_PRODUCT_ID not in", values, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdBetween(Integer value1, Integer value2) {
            addCriterion("FINANCIAL_PRODUCT_ID between", value1, value2, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FINANCIAL_PRODUCT_ID not between", value1, value2, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIsNull() {
            addCriterion("SECURITY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIsNotNull() {
            addCriterion("SECURITY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeEqualTo(String value) {
            addCriterion("SECURITY_CODE =", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotEqualTo(String value) {
            addCriterion("SECURITY_CODE <>", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeGreaterThan(String value) {
            addCriterion("SECURITY_CODE >", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SECURITY_CODE >=", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLessThan(String value) {
            addCriterion("SECURITY_CODE <", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLessThanOrEqualTo(String value) {
            addCriterion("SECURITY_CODE <=", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLike(String value) {
            addCriterion("SECURITY_CODE like", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotLike(String value) {
            addCriterion("SECURITY_CODE not like", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIn(List<String> values) {
            addCriterion("SECURITY_CODE in", values, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotIn(List<String> values) {
            addCriterion("SECURITY_CODE not in", values, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeBetween(String value1, String value2) {
            addCriterion("SECURITY_CODE between", value1, value2, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotBetween(String value1, String value2) {
            addCriterion("SECURITY_CODE not between", value1, value2, "securityCode");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNull() {
            addCriterion("TRADE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNotNull() {
            addCriterion("TRADE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDateEqualTo(Integer value) {
            addCriterion("TRADE_DATE =", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotEqualTo(Integer value) {
            addCriterion("TRADE_DATE <>", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThan(Integer value) {
            addCriterion("TRADE_DATE >", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("TRADE_DATE >=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThan(Integer value) {
            addCriterion("TRADE_DATE <", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThanOrEqualTo(Integer value) {
            addCriterion("TRADE_DATE <=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIn(List<Integer> values) {
            addCriterion("TRADE_DATE in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotIn(List<Integer> values) {
            addCriterion("TRADE_DATE not in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateBetween(Integer value1, Integer value2) {
            addCriterion("TRADE_DATE between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotBetween(Integer value1, Integer value2) {
            addCriterion("TRADE_DATE not between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNull() {
            addCriterion("VALUE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNotNull() {
            addCriterion("VALUE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andValueDateEqualTo(Integer value) {
            addCriterion("VALUE_DATE =", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotEqualTo(Integer value) {
            addCriterion("VALUE_DATE <>", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThan(Integer value) {
            addCriterion("VALUE_DATE >", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("VALUE_DATE >=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThan(Integer value) {
            addCriterion("VALUE_DATE <", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThanOrEqualTo(Integer value) {
            addCriterion("VALUE_DATE <=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIn(List<Integer> values) {
            addCriterion("VALUE_DATE in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotIn(List<Integer> values) {
            addCriterion("VALUE_DATE not in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateBetween(Integer value1, Integer value2) {
            addCriterion("VALUE_DATE between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotBetween(Integer value1, Integer value2) {
            addCriterion("VALUE_DATE not between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andNominalIsNull() {
            addCriterion("NOMINAL is null");
            return (Criteria) this;
        }

        public Criteria andNominalIsNotNull() {
            addCriterion("NOMINAL is not null");
            return (Criteria) this;
        }

        public Criteria andNominalEqualTo(BigDecimal value) {
            addCriterion("NOMINAL =", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotEqualTo(BigDecimal value) {
            addCriterion("NOMINAL <>", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalGreaterThan(BigDecimal value) {
            addCriterion("NOMINAL >", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NOMINAL >=", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalLessThan(BigDecimal value) {
            addCriterion("NOMINAL <", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NOMINAL <=", value, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalIn(List<BigDecimal> values) {
            addCriterion("NOMINAL in", values, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotIn(List<BigDecimal> values) {
            addCriterion("NOMINAL not in", values, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NOMINAL between", value1, value2, "nominal");
            return (Criteria) this;
        }

        public Criteria andNominalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NOMINAL not between", value1, value2, "nominal");
            return (Criteria) this;
        }

        public Criteria andClearPriceIsNull() {
            addCriterion("CLEAR_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andClearPriceIsNotNull() {
            addCriterion("CLEAR_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andClearPriceEqualTo(BigDecimal value) {
            addCriterion("CLEAR_PRICE =", value, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceNotEqualTo(BigDecimal value) {
            addCriterion("CLEAR_PRICE <>", value, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceGreaterThan(BigDecimal value) {
            addCriterion("CLEAR_PRICE >", value, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CLEAR_PRICE >=", value, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceLessThan(BigDecimal value) {
            addCriterion("CLEAR_PRICE <", value, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CLEAR_PRICE <=", value, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceIn(List<BigDecimal> values) {
            addCriterion("CLEAR_PRICE in", values, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceNotIn(List<BigDecimal> values) {
            addCriterion("CLEAR_PRICE not in", values, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLEAR_PRICE between", value1, value2, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andClearPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLEAR_PRICE not between", value1, value2, "clearPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceIsNull() {
            addCriterion("DIRTY_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceIsNotNull() {
            addCriterion("DIRTY_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceEqualTo(BigDecimal value) {
            addCriterion("DIRTY_PRICE =", value, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceNotEqualTo(BigDecimal value) {
            addCriterion("DIRTY_PRICE <>", value, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceGreaterThan(BigDecimal value) {
            addCriterion("DIRTY_PRICE >", value, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DIRTY_PRICE >=", value, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceLessThan(BigDecimal value) {
            addCriterion("DIRTY_PRICE <", value, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DIRTY_PRICE <=", value, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceIn(List<BigDecimal> values) {
            addCriterion("DIRTY_PRICE in", values, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceNotIn(List<BigDecimal> values) {
            addCriterion("DIRTY_PRICE not in", values, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DIRTY_PRICE between", value1, value2, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andDirtyPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DIRTY_PRICE not between", value1, value2, "dirtyPrice");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("INTEREST is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("INTEREST is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(BigDecimal value) {
            addCriterion("INTEREST =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(BigDecimal value) {
            addCriterion("INTEREST <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(BigDecimal value) {
            addCriterion("INTEREST >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(BigDecimal value) {
            addCriterion("INTEREST <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<BigDecimal> values) {
            addCriterion("INTEREST in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<BigDecimal> values) {
            addCriterion("INTEREST not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andSettleAmountIsNull() {
            addCriterion("SETTLE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andSettleAmountIsNotNull() {
            addCriterion("SETTLE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAmountEqualTo(BigDecimal value) {
            addCriterion("SETTLE_AMOUNT =", value, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountNotEqualTo(BigDecimal value) {
            addCriterion("SETTLE_AMOUNT <>", value, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountGreaterThan(BigDecimal value) {
            addCriterion("SETTLE_AMOUNT >", value, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SETTLE_AMOUNT >=", value, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountLessThan(BigDecimal value) {
            addCriterion("SETTLE_AMOUNT <", value, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SETTLE_AMOUNT <=", value, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountIn(List<BigDecimal> values) {
            addCriterion("SETTLE_AMOUNT in", values, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountNotIn(List<BigDecimal> values) {
            addCriterion("SETTLE_AMOUNT not in", values, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SETTLE_AMOUNT between", value1, value2, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SETTLE_AMOUNT not between", value1, value2, "settleAmount");
            return (Criteria) this;
        }

        public Criteria andSettleTypeIsNull() {
            addCriterion("SETTLE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSettleTypeIsNotNull() {
            addCriterion("SETTLE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSettleTypeEqualTo(String value) {
            addCriterion("SETTLE_TYPE =", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotEqualTo(String value) {
            addCriterion("SETTLE_TYPE <>", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeGreaterThan(String value) {
            addCriterion("SETTLE_TYPE >", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_TYPE >=", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeLessThan(String value) {
            addCriterion("SETTLE_TYPE <", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_TYPE <=", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeLike(String value) {
            addCriterion("SETTLE_TYPE like", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotLike(String value) {
            addCriterion("SETTLE_TYPE not like", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeIn(List<String> values) {
            addCriterion("SETTLE_TYPE in", values, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotIn(List<String> values) {
            addCriterion("SETTLE_TYPE not in", values, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeBetween(String value1, String value2) {
            addCriterion("SETTLE_TYPE between", value1, value2, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotBetween(String value1, String value2) {
            addCriterion("SETTLE_TYPE not between", value1, value2, "settleType");
            return (Criteria) this;
        }

        public Criteria andYieldIsNull() {
            addCriterion("YIELD is null");
            return (Criteria) this;
        }

        public Criteria andYieldIsNotNull() {
            addCriterion("YIELD is not null");
            return (Criteria) this;
        }

        public Criteria andYieldEqualTo(BigDecimal value) {
            addCriterion("YIELD =", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotEqualTo(BigDecimal value) {
            addCriterion("YIELD <>", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldGreaterThan(BigDecimal value) {
            addCriterion("YIELD >", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YIELD >=", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldLessThan(BigDecimal value) {
            addCriterion("YIELD <", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YIELD <=", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldIn(List<BigDecimal> values) {
            addCriterion("YIELD in", values, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotIn(List<BigDecimal> values) {
            addCriterion("YIELD not in", values, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YIELD between", value1, value2, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YIELD not between", value1, value2, "yield");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("DIRECTION is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("DIRECTION is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(String value) {
            addCriterion("DIRECTION =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(String value) {
            addCriterion("DIRECTION <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(String value) {
            addCriterion("DIRECTION >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("DIRECTION >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(String value) {
            addCriterion("DIRECTION <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(String value) {
            addCriterion("DIRECTION <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(String value) {
            addCriterion("DIRECTION like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(String value) {
            addCriterion("DIRECTION not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<String> values) {
            addCriterion("DIRECTION in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<String> values) {
            addCriterion("DIRECTION not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(String value1, String value2) {
            addCriterion("DIRECTION between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(String value1, String value2) {
            addCriterion("DIRECTION not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andCounterpartyIsNull() {
            addCriterion("COUNTERPARTY is null");
            return (Criteria) this;
        }

        public Criteria andCounterpartyIsNotNull() {
            addCriterion("COUNTERPARTY is not null");
            return (Criteria) this;
        }

        public Criteria andCounterpartyEqualTo(String value) {
            addCriterion("COUNTERPARTY =", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyNotEqualTo(String value) {
            addCriterion("COUNTERPARTY <>", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyGreaterThan(String value) {
            addCriterion("COUNTERPARTY >", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTERPARTY >=", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyLessThan(String value) {
            addCriterion("COUNTERPARTY <", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyLessThanOrEqualTo(String value) {
            addCriterion("COUNTERPARTY <=", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyLike(String value) {
            addCriterion("COUNTERPARTY like", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyNotLike(String value) {
            addCriterion("COUNTERPARTY not like", value, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyIn(List<String> values) {
            addCriterion("COUNTERPARTY in", values, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyNotIn(List<String> values) {
            addCriterion("COUNTERPARTY not in", values, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyBetween(String value1, String value2) {
            addCriterion("COUNTERPARTY between", value1, value2, "counterparty");
            return (Criteria) this;
        }

        public Criteria andCounterpartyNotBetween(String value1, String value2) {
            addCriterion("COUNTERPARTY not between", value1, value2, "counterparty");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(Integer value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(Integer value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(Integer value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(Integer value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<Integer> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<Integer> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 10 13:48:35 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}