package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FinancialProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public FinancialProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFinancialProductIdIsNull() {
            addCriterion("FINANCIAL_PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIsNotNull() {
            addCriterion("FINANCIAL_PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID =", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID <>", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdGreaterThan(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID >", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID >=", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLessThan(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID <", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("FINANCIAL_PRODUCT_ID <=", value, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdIn(List<Integer> values) {
            addCriterion("FINANCIAL_PRODUCT_ID in", values, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotIn(List<Integer> values) {
            addCriterion("FINANCIAL_PRODUCT_ID not in", values, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdBetween(Integer value1, Integer value2) {
            addCriterion("FINANCIAL_PRODUCT_ID between", value1, value2, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andFinancialProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FINANCIAL_PRODUCT_ID not between", value1, value2, "financialProductId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNull() {
            addCriterion("BRANCH_ID is null");
            return (Criteria) this;
        }

        public Criteria andBranchIdIsNotNull() {
            addCriterion("BRANCH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBranchIdEqualTo(Integer value) {
            addCriterion("BRANCH_ID =", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotEqualTo(Integer value) {
            addCriterion("BRANCH_ID <>", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThan(Integer value) {
            addCriterion("BRANCH_ID >", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BRANCH_ID >=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThan(Integer value) {
            addCriterion("BRANCH_ID <", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdLessThanOrEqualTo(Integer value) {
            addCriterion("BRANCH_ID <=", value, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdIn(List<Integer> values) {
            addCriterion("BRANCH_ID in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotIn(List<Integer> values) {
            addCriterion("BRANCH_ID not in", values, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdBetween(Integer value1, Integer value2) {
            addCriterion("BRANCH_ID between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andBranchIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BRANCH_ID not between", value1, value2, "branchId");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("DURATION is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("DURATION is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("DURATION =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("DURATION <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("DURATION >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("DURATION >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("DURATION <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("DURATION <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("DURATION in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("DURATION not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("DURATION between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("DURATION not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Integer value) {
            addCriterion("START_DATE =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Integer value) {
            addCriterion("START_DATE <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Integer value) {
            addCriterion("START_DATE >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("START_DATE >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Integer value) {
            addCriterion("START_DATE <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Integer value) {
            addCriterion("START_DATE <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Integer> values) {
            addCriterion("START_DATE in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Integer> values) {
            addCriterion("START_DATE not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Integer value1, Integer value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Integer value1, Integer value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Integer value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Integer value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Integer value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Integer value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Integer value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Integer> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Integer> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Integer value1, Integer value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Integer value1, Integer value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNull() {
            addCriterion("CURRENCY_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIsNotNull() {
            addCriterion("CURRENCY_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeEqualTo(String value) {
            addCriterion("CURRENCY_TYPE =", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotEqualTo(String value) {
            addCriterion("CURRENCY_TYPE <>", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThan(String value) {
            addCriterion("CURRENCY_TYPE >", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY_TYPE >=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThan(String value) {
            addCriterion("CURRENCY_TYPE <", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY_TYPE <=", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeLike(String value) {
            addCriterion("CURRENCY_TYPE like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotLike(String value) {
            addCriterion("CURRENCY_TYPE not like", value, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeIn(List<String> values) {
            addCriterion("CURRENCY_TYPE in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotIn(List<String> values) {
            addCriterion("CURRENCY_TYPE not in", values, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeBetween(String value1, String value2) {
            addCriterion("CURRENCY_TYPE between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andCurrencyTypeNotBetween(String value1, String value2) {
            addCriterion("CURRENCY_TYPE not between", value1, value2, "currencyType");
            return (Criteria) this;
        }

        public Criteria andIssueAmountIsNull() {
            addCriterion("ISSUE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andIssueAmountIsNotNull() {
            addCriterion("ISSUE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andIssueAmountEqualTo(BigDecimal value) {
            addCriterion("ISSUE_AMOUNT =", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountNotEqualTo(BigDecimal value) {
            addCriterion("ISSUE_AMOUNT <>", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountGreaterThan(BigDecimal value) {
            addCriterion("ISSUE_AMOUNT >", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ISSUE_AMOUNT >=", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountLessThan(BigDecimal value) {
            addCriterion("ISSUE_AMOUNT <", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ISSUE_AMOUNT <=", value, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountIn(List<BigDecimal> values) {
            addCriterion("ISSUE_AMOUNT in", values, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountNotIn(List<BigDecimal> values) {
            addCriterion("ISSUE_AMOUNT not in", values, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISSUE_AMOUNT between", value1, value2, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andIssueAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ISSUE_AMOUNT not between", value1, value2, "issueAmount");
            return (Criteria) this;
        }

        public Criteria andYieldIsNull() {
            addCriterion("YIELD is null");
            return (Criteria) this;
        }

        public Criteria andYieldIsNotNull() {
            addCriterion("YIELD is not null");
            return (Criteria) this;
        }

        public Criteria andYieldEqualTo(BigDecimal value) {
            addCriterion("YIELD =", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotEqualTo(BigDecimal value) {
            addCriterion("YIELD <>", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldGreaterThan(BigDecimal value) {
            addCriterion("YIELD >", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YIELD >=", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldLessThan(BigDecimal value) {
            addCriterion("YIELD <", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YIELD <=", value, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldIn(List<BigDecimal> values) {
            addCriterion("YIELD in", values, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotIn(List<BigDecimal> values) {
            addCriterion("YIELD not in", values, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YIELD between", value1, value2, "yield");
            return (Criteria) this;
        }

        public Criteria andYieldNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YIELD not between", value1, value2, "yield");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateIsNull() {
            addCriterion("RAISE_START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateIsNotNull() {
            addCriterion("RAISE_START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateEqualTo(Integer value) {
            addCriterion("RAISE_START_DATE =", value, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateNotEqualTo(Integer value) {
            addCriterion("RAISE_START_DATE <>", value, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateGreaterThan(Integer value) {
            addCriterion("RAISE_START_DATE >", value, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("RAISE_START_DATE >=", value, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateLessThan(Integer value) {
            addCriterion("RAISE_START_DATE <", value, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateLessThanOrEqualTo(Integer value) {
            addCriterion("RAISE_START_DATE <=", value, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateIn(List<Integer> values) {
            addCriterion("RAISE_START_DATE in", values, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateNotIn(List<Integer> values) {
            addCriterion("RAISE_START_DATE not in", values, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateBetween(Integer value1, Integer value2) {
            addCriterion("RAISE_START_DATE between", value1, value2, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseStartDateNotBetween(Integer value1, Integer value2) {
            addCriterion("RAISE_START_DATE not between", value1, value2, "raiseStartDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateIsNull() {
            addCriterion("RAISE_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateIsNotNull() {
            addCriterion("RAISE_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateEqualTo(Integer value) {
            addCriterion("RAISE_END_DATE =", value, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateNotEqualTo(Integer value) {
            addCriterion("RAISE_END_DATE <>", value, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateGreaterThan(Integer value) {
            addCriterion("RAISE_END_DATE >", value, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("RAISE_END_DATE >=", value, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateLessThan(Integer value) {
            addCriterion("RAISE_END_DATE <", value, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateLessThanOrEqualTo(Integer value) {
            addCriterion("RAISE_END_DATE <=", value, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateIn(List<Integer> values) {
            addCriterion("RAISE_END_DATE in", values, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateNotIn(List<Integer> values) {
            addCriterion("RAISE_END_DATE not in", values, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateBetween(Integer value1, Integer value2) {
            addCriterion("RAISE_END_DATE between", value1, value2, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andRaiseEndDateNotBetween(Integer value1, Integer value2) {
            addCriterion("RAISE_END_DATE not between", value1, value2, "raiseEndDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateIsNull() {
            addCriterion("PAYMENT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPaymentDateIsNotNull() {
            addCriterion("PAYMENT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentDateEqualTo(String value) {
            addCriterion("PAYMENT_DATE =", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateNotEqualTo(String value) {
            addCriterion("PAYMENT_DATE <>", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateGreaterThan(String value) {
            addCriterion("PAYMENT_DATE >", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateGreaterThanOrEqualTo(String value) {
            addCriterion("PAYMENT_DATE >=", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateLessThan(String value) {
            addCriterion("PAYMENT_DATE <", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateLessThanOrEqualTo(String value) {
            addCriterion("PAYMENT_DATE <=", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateLike(String value) {
            addCriterion("PAYMENT_DATE like", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateNotLike(String value) {
            addCriterion("PAYMENT_DATE not like", value, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateIn(List<String> values) {
            addCriterion("PAYMENT_DATE in", values, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateNotIn(List<String> values) {
            addCriterion("PAYMENT_DATE not in", values, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateBetween(String value1, String value2) {
            addCriterion("PAYMENT_DATE between", value1, value2, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andPaymentDateNotBetween(String value1, String value2) {
            addCriterion("PAYMENT_DATE not between", value1, value2, "paymentDate");
            return (Criteria) this;
        }

        public Criteria andHostFeeIsNull() {
            addCriterion("HOST_FEE is null");
            return (Criteria) this;
        }

        public Criteria andHostFeeIsNotNull() {
            addCriterion("HOST_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andHostFeeEqualTo(BigDecimal value) {
            addCriterion("HOST_FEE =", value, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeNotEqualTo(BigDecimal value) {
            addCriterion("HOST_FEE <>", value, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeGreaterThan(BigDecimal value) {
            addCriterion("HOST_FEE >", value, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HOST_FEE >=", value, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeLessThan(BigDecimal value) {
            addCriterion("HOST_FEE <", value, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HOST_FEE <=", value, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeIn(List<BigDecimal> values) {
            addCriterion("HOST_FEE in", values, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeNotIn(List<BigDecimal> values) {
            addCriterion("HOST_FEE not in", values, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HOST_FEE between", value1, value2, "hostFee");
            return (Criteria) this;
        }

        public Criteria andHostFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HOST_FEE not between", value1, value2, "hostFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeIsNull() {
            addCriterion("MANAGE_FEE is null");
            return (Criteria) this;
        }

        public Criteria andManageFeeIsNotNull() {
            addCriterion("MANAGE_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andManageFeeEqualTo(BigDecimal value) {
            addCriterion("MANAGE_FEE =", value, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeNotEqualTo(BigDecimal value) {
            addCriterion("MANAGE_FEE <>", value, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeGreaterThan(BigDecimal value) {
            addCriterion("MANAGE_FEE >", value, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MANAGE_FEE >=", value, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeLessThan(BigDecimal value) {
            addCriterion("MANAGE_FEE <", value, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MANAGE_FEE <=", value, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeIn(List<BigDecimal> values) {
            addCriterion("MANAGE_FEE in", values, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeNotIn(List<BigDecimal> values) {
            addCriterion("MANAGE_FEE not in", values, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MANAGE_FEE between", value1, value2, "manageFee");
            return (Criteria) this;
        }

        public Criteria andManageFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MANAGE_FEE not between", value1, value2, "manageFee");
            return (Criteria) this;
        }

        public Criteria andProtectTypeIsNull() {
            addCriterion("PROTECT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andProtectTypeIsNotNull() {
            addCriterion("PROTECT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProtectTypeEqualTo(String value) {
            addCriterion("PROTECT_TYPE =", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeNotEqualTo(String value) {
            addCriterion("PROTECT_TYPE <>", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeGreaterThan(String value) {
            addCriterion("PROTECT_TYPE >", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PROTECT_TYPE >=", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeLessThan(String value) {
            addCriterion("PROTECT_TYPE <", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeLessThanOrEqualTo(String value) {
            addCriterion("PROTECT_TYPE <=", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeLike(String value) {
            addCriterion("PROTECT_TYPE like", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeNotLike(String value) {
            addCriterion("PROTECT_TYPE not like", value, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeIn(List<String> values) {
            addCriterion("PROTECT_TYPE in", values, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeNotIn(List<String> values) {
            addCriterion("PROTECT_TYPE not in", values, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeBetween(String value1, String value2) {
            addCriterion("PROTECT_TYPE between", value1, value2, "protectType");
            return (Criteria) this;
        }

        public Criteria andProtectTypeNotBetween(String value1, String value2) {
            addCriterion("PROTECT_TYPE not between", value1, value2, "protectType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeIsNull() {
            addCriterion("TARGET_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTargetTypeIsNotNull() {
            addCriterion("TARGET_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTargetTypeEqualTo(String value) {
            addCriterion("TARGET_TYPE =", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotEqualTo(String value) {
            addCriterion("TARGET_TYPE <>", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeGreaterThan(String value) {
            addCriterion("TARGET_TYPE >", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET_TYPE >=", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeLessThan(String value) {
            addCriterion("TARGET_TYPE <", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeLessThanOrEqualTo(String value) {
            addCriterion("TARGET_TYPE <=", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeLike(String value) {
            addCriterion("TARGET_TYPE like", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotLike(String value) {
            addCriterion("TARGET_TYPE not like", value, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeIn(List<String> values) {
            addCriterion("TARGET_TYPE in", values, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotIn(List<String> values) {
            addCriterion("TARGET_TYPE not in", values, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeBetween(String value1, String value2) {
            addCriterion("TARGET_TYPE between", value1, value2, "targetType");
            return (Criteria) this;
        }

        public Criteria andTargetTypeNotBetween(String value1, String value2) {
            addCriterion("TARGET_TYPE not between", value1, value2, "targetType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeIsNull() {
            addCriterion("REDEEM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeIsNotNull() {
            addCriterion("REDEEM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeEqualTo(String value) {
            addCriterion("REDEEM_TYPE =", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeNotEqualTo(String value) {
            addCriterion("REDEEM_TYPE <>", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeGreaterThan(String value) {
            addCriterion("REDEEM_TYPE >", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REDEEM_TYPE >=", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeLessThan(String value) {
            addCriterion("REDEEM_TYPE <", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeLessThanOrEqualTo(String value) {
            addCriterion("REDEEM_TYPE <=", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeLike(String value) {
            addCriterion("REDEEM_TYPE like", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeNotLike(String value) {
            addCriterion("REDEEM_TYPE not like", value, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeIn(List<String> values) {
            addCriterion("REDEEM_TYPE in", values, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeNotIn(List<String> values) {
            addCriterion("REDEEM_TYPE not in", values, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeBetween(String value1, String value2) {
            addCriterion("REDEEM_TYPE between", value1, value2, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRedeemTypeNotBetween(String value1, String value2) {
            addCriterion("REDEEM_TYPE not between", value1, value2, "redeemType");
            return (Criteria) this;
        }

        public Criteria andRattingIsNull() {
            addCriterion("RATTING is null");
            return (Criteria) this;
        }

        public Criteria andRattingIsNotNull() {
            addCriterion("RATTING is not null");
            return (Criteria) this;
        }

        public Criteria andRattingEqualTo(String value) {
            addCriterion("RATTING =", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingNotEqualTo(String value) {
            addCriterion("RATTING <>", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingGreaterThan(String value) {
            addCriterion("RATTING >", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingGreaterThanOrEqualTo(String value) {
            addCriterion("RATTING >=", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingLessThan(String value) {
            addCriterion("RATTING <", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingLessThanOrEqualTo(String value) {
            addCriterion("RATTING <=", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingLike(String value) {
            addCriterion("RATTING like", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingNotLike(String value) {
            addCriterion("RATTING not like", value, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingIn(List<String> values) {
            addCriterion("RATTING in", values, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingNotIn(List<String> values) {
            addCriterion("RATTING not in", values, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingBetween(String value1, String value2) {
            addCriterion("RATTING between", value1, value2, "ratting");
            return (Criteria) this;
        }

        public Criteria andRattingNotBetween(String value1, String value2) {
            addCriterion("RATTING not between", value1, value2, "ratting");
            return (Criteria) this;
        }

        public Criteria andTargetIsNull() {
            addCriterion("TARGET is null");
            return (Criteria) this;
        }

        public Criteria andTargetIsNotNull() {
            addCriterion("TARGET is not null");
            return (Criteria) this;
        }

        public Criteria andTargetEqualTo(String value) {
            addCriterion("TARGET =", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotEqualTo(String value) {
            addCriterion("TARGET <>", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThan(String value) {
            addCriterion("TARGET >", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET >=", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLessThan(String value) {
            addCriterion("TARGET <", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLessThanOrEqualTo(String value) {
            addCriterion("TARGET <=", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLike(String value) {
            addCriterion("TARGET like", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotLike(String value) {
            addCriterion("TARGET not like", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetIn(List<String> values) {
            addCriterion("TARGET in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotIn(List<String> values) {
            addCriterion("TARGET not in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetBetween(String value1, String value2) {
            addCriterion("TARGET between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotBetween(String value1, String value2) {
            addCriterion("TARGET not between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountIsNull() {
            addCriterion("ENNTER_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountIsNotNull() {
            addCriterion("ENNTER_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountEqualTo(String value) {
            addCriterion("ENNTER_AMOUNT =", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountNotEqualTo(String value) {
            addCriterion("ENNTER_AMOUNT <>", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountGreaterThan(String value) {
            addCriterion("ENNTER_AMOUNT >", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountGreaterThanOrEqualTo(String value) {
            addCriterion("ENNTER_AMOUNT >=", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountLessThan(String value) {
            addCriterion("ENNTER_AMOUNT <", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountLessThanOrEqualTo(String value) {
            addCriterion("ENNTER_AMOUNT <=", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountLike(String value) {
            addCriterion("ENNTER_AMOUNT like", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountNotLike(String value) {
            addCriterion("ENNTER_AMOUNT not like", value, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountIn(List<String> values) {
            addCriterion("ENNTER_AMOUNT in", values, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountNotIn(List<String> values) {
            addCriterion("ENNTER_AMOUNT not in", values, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountBetween(String value1, String value2) {
            addCriterion("ENNTER_AMOUNT between", value1, value2, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andEnnterAmountNotBetween(String value1, String value2) {
            addCriterion("ENNTER_AMOUNT not between", value1, value2, "ennterAmount");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionIsNull() {
            addCriterion("YIELD_FUNCTION is null");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionIsNotNull() {
            addCriterion("YIELD_FUNCTION is not null");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionEqualTo(String value) {
            addCriterion("YIELD_FUNCTION =", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionNotEqualTo(String value) {
            addCriterion("YIELD_FUNCTION <>", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionGreaterThan(String value) {
            addCriterion("YIELD_FUNCTION >", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionGreaterThanOrEqualTo(String value) {
            addCriterion("YIELD_FUNCTION >=", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionLessThan(String value) {
            addCriterion("YIELD_FUNCTION <", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionLessThanOrEqualTo(String value) {
            addCriterion("YIELD_FUNCTION <=", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionLike(String value) {
            addCriterion("YIELD_FUNCTION like", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionNotLike(String value) {
            addCriterion("YIELD_FUNCTION not like", value, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionIn(List<String> values) {
            addCriterion("YIELD_FUNCTION in", values, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionNotIn(List<String> values) {
            addCriterion("YIELD_FUNCTION not in", values, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionBetween(String value1, String value2) {
            addCriterion("YIELD_FUNCTION between", value1, value2, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andYieldFunctionNotBetween(String value1, String value2) {
            addCriterion("YIELD_FUNCTION not between", value1, value2, "yieldFunction");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("NOTE is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("NOTE is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("NOTE =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("NOTE <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("NOTE >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("NOTE >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("NOTE <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("NOTE <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("NOTE like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("NOTE not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("NOTE in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("NOTE not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("NOTE between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("NOTE not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(Integer value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(Integer value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(Integer value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(Integer value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<Integer> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<Integer> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 10 14:33:02 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}