package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinancialProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer financialProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.CODE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.NAME
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.DURATION
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.START_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.END_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.CURRENCY_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.ISSUE_AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private BigDecimal issueAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.YIELD
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private BigDecimal yield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.RAISE_START_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer raiseStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.RAISE_END_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer raiseEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.PAYMENT_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.HOST_FEE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private BigDecimal hostFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.MANAGE_FEE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private BigDecimal manageFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.PROTECT_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String protectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.TARGET_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.REDEEM_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String redeemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.RATTING
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String ratting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.TARGET
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.ENNTER_AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String ennterAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.YIELD_FUNCTION
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String yieldFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.NOTE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FINANCIAL_PRODUCT.MODIFY_USER
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    private Integer modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.FINANCIAL_PRODUCT_ID
     *
     * @return the value of FINANCIAL_PRODUCT.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getFinancialProductId() {
        return financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.FINANCIAL_PRODUCT_ID
     *
     * @param financialProductId the value for FINANCIAL_PRODUCT.FINANCIAL_PRODUCT_ID
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setFinancialProductId(Integer financialProductId) {
        this.financialProductId = financialProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.BRANCH_ID
     *
     * @return the value of FINANCIAL_PRODUCT.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.BRANCH_ID
     *
     * @param branchId the value for FINANCIAL_PRODUCT.BRANCH_ID
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.CODE
     *
     * @return the value of FINANCIAL_PRODUCT.CODE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.CODE
     *
     * @param code the value for FINANCIAL_PRODUCT.CODE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.NAME
     *
     * @return the value of FINANCIAL_PRODUCT.NAME
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.NAME
     *
     * @param name the value for FINANCIAL_PRODUCT.NAME
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.DURATION
     *
     * @return the value of FINANCIAL_PRODUCT.DURATION
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.DURATION
     *
     * @param duration the value for FINANCIAL_PRODUCT.DURATION
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.START_DATE
     *
     * @return the value of FINANCIAL_PRODUCT.START_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.START_DATE
     *
     * @param startDate the value for FINANCIAL_PRODUCT.START_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setStartDate(Integer startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.END_DATE
     *
     * @return the value of FINANCIAL_PRODUCT.END_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.END_DATE
     *
     * @param endDate the value for FINANCIAL_PRODUCT.END_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setEndDate(Integer endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.CURRENCY_TYPE
     *
     * @return the value of FINANCIAL_PRODUCT.CURRENCY_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.CURRENCY_TYPE
     *
     * @param currencyType the value for FINANCIAL_PRODUCT.CURRENCY_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.ISSUE_AMOUNT
     *
     * @return the value of FINANCIAL_PRODUCT.ISSUE_AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public BigDecimal getIssueAmount() {
        return issueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.ISSUE_AMOUNT
     *
     * @param issueAmount the value for FINANCIAL_PRODUCT.ISSUE_AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setIssueAmount(BigDecimal issueAmount) {
        this.issueAmount = issueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.YIELD
     *
     * @return the value of FINANCIAL_PRODUCT.YIELD
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public BigDecimal getYield() {
        return yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.YIELD
     *
     * @param yield the value for FINANCIAL_PRODUCT.YIELD
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setYield(BigDecimal yield) {
        this.yield = yield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.RAISE_START_DATE
     *
     * @return the value of FINANCIAL_PRODUCT.RAISE_START_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getRaiseStartDate() {
        return raiseStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.RAISE_START_DATE
     *
     * @param raiseStartDate the value for FINANCIAL_PRODUCT.RAISE_START_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setRaiseStartDate(Integer raiseStartDate) {
        this.raiseStartDate = raiseStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.RAISE_END_DATE
     *
     * @return the value of FINANCIAL_PRODUCT.RAISE_END_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getRaiseEndDate() {
        return raiseEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.RAISE_END_DATE
     *
     * @param raiseEndDate the value for FINANCIAL_PRODUCT.RAISE_END_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setRaiseEndDate(Integer raiseEndDate) {
        this.raiseEndDate = raiseEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.PAYMENT_DATE
     *
     * @return the value of FINANCIAL_PRODUCT.PAYMENT_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.PAYMENT_DATE
     *
     * @param paymentDate the value for FINANCIAL_PRODUCT.PAYMENT_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate == null ? null : paymentDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.HOST_FEE
     *
     * @return the value of FINANCIAL_PRODUCT.HOST_FEE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public BigDecimal getHostFee() {
        return hostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.HOST_FEE
     *
     * @param hostFee the value for FINANCIAL_PRODUCT.HOST_FEE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setHostFee(BigDecimal hostFee) {
        this.hostFee = hostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.MANAGE_FEE
     *
     * @return the value of FINANCIAL_PRODUCT.MANAGE_FEE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public BigDecimal getManageFee() {
        return manageFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.MANAGE_FEE
     *
     * @param manageFee the value for FINANCIAL_PRODUCT.MANAGE_FEE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setManageFee(BigDecimal manageFee) {
        this.manageFee = manageFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.PROTECT_TYPE
     *
     * @return the value of FINANCIAL_PRODUCT.PROTECT_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getProtectType() {
        return protectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.PROTECT_TYPE
     *
     * @param protectType the value for FINANCIAL_PRODUCT.PROTECT_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setProtectType(String protectType) {
        this.protectType = protectType == null ? null : protectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.TARGET_TYPE
     *
     * @return the value of FINANCIAL_PRODUCT.TARGET_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.TARGET_TYPE
     *
     * @param targetType the value for FINANCIAL_PRODUCT.TARGET_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.REDEEM_TYPE
     *
     * @return the value of FINANCIAL_PRODUCT.REDEEM_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getRedeemType() {
        return redeemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.REDEEM_TYPE
     *
     * @param redeemType the value for FINANCIAL_PRODUCT.REDEEM_TYPE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setRedeemType(String redeemType) {
        this.redeemType = redeemType == null ? null : redeemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.RATTING
     *
     * @return the value of FINANCIAL_PRODUCT.RATTING
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getRatting() {
        return ratting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.RATTING
     *
     * @param ratting the value for FINANCIAL_PRODUCT.RATTING
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setRatting(String ratting) {
        this.ratting = ratting == null ? null : ratting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.TARGET
     *
     * @return the value of FINANCIAL_PRODUCT.TARGET
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.TARGET
     *
     * @param target the value for FINANCIAL_PRODUCT.TARGET
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.ENNTER_AMOUNT
     *
     * @return the value of FINANCIAL_PRODUCT.ENNTER_AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getEnnterAmount() {
        return ennterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.ENNTER_AMOUNT
     *
     * @param ennterAmount the value for FINANCIAL_PRODUCT.ENNTER_AMOUNT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setEnnterAmount(String ennterAmount) {
        this.ennterAmount = ennterAmount == null ? null : ennterAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.YIELD_FUNCTION
     *
     * @return the value of FINANCIAL_PRODUCT.YIELD_FUNCTION
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getYieldFunction() {
        return yieldFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.YIELD_FUNCTION
     *
     * @param yieldFunction the value for FINANCIAL_PRODUCT.YIELD_FUNCTION
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setYieldFunction(String yieldFunction) {
        this.yieldFunction = yieldFunction == null ? null : yieldFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.NOTE
     *
     * @return the value of FINANCIAL_PRODUCT.NOTE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.NOTE
     *
     * @param note the value for FINANCIAL_PRODUCT.NOTE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.MODIFY_DATE
     *
     * @return the value of FINANCIAL_PRODUCT.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.MODIFY_DATE
     *
     * @param modifyDate the value for FINANCIAL_PRODUCT.MODIFY_DATE
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCIAL_PRODUCT.MODIFY_USER
     *
     * @return the value of FINANCIAL_PRODUCT.MODIFY_USER
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCIAL_PRODUCT.MODIFY_USER
     *
     * @param modifyUser the value for FINANCIAL_PRODUCT.MODIFY_USER
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }
}