package com.comstar.mars.entity;

public class MyTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_TABLE.MY_TABLE_ID
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    private Integer myTableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_TABLE.NAME
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MY_TABLE.STATUS
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_TABLE.MY_TABLE_ID
     *
     * @return the value of MY_TABLE.MY_TABLE_ID
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    public Integer getMyTableId() {
        return myTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_TABLE.MY_TABLE_ID
     *
     * @param myTableId the value for MY_TABLE.MY_TABLE_ID
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    public void setMyTableId(Integer myTableId) {
        this.myTableId = myTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_TABLE.NAME
     *
     * @return the value of MY_TABLE.NAME
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_TABLE.NAME
     *
     * @param name the value for MY_TABLE.NAME
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MY_TABLE.STATUS
     *
     * @return the value of MY_TABLE.STATUS
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MY_TABLE.STATUS
     *
     * @param status the value for MY_TABLE.STATUS
     *
     * @mbggenerated Thu Dec 24 11:23:12 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}