package com.comstar.mars.entity;

public class RolePrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_PRIVILEGE.ROLE_ID
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_PRIVILEGE.PRIVILEGE_ID
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    private Integer privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_PRIVILEGE.ROLE_ID
     *
     * @return the value of SYS_ROLE_PRIVILEGE.ROLE_ID
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_PRIVILEGE.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE_PRIVILEGE.ROLE_ID
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_PRIVILEGE.PRIVILEGE_ID
     *
     * @return the value of SYS_ROLE_PRIVILEGE.PRIVILEGE_ID
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    public Integer getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_PRIVILEGE.PRIVILEGE_ID
     *
     * @param privilegeId the value for SYS_ROLE_PRIVILEGE.PRIVILEGE_ID
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
}