package com.comstar.mars.entity;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.DESCRIPTION
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.BRANCH_ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private Integer branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ID
     *
     * @return the value of SYS_ROLE.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ID
     *
     * @param id the value for SYS_ROLE.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.NAME
     *
     * @return the value of SYS_ROLE.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.NAME
     *
     * @param name the value for SYS_ROLE.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.DESCRIPTION
     *
     * @return the value of SYS_ROLE.DESCRIPTION
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.DESCRIPTION
     *
     * @param description the value for SYS_ROLE.DESCRIPTION
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.BRANCH_ID
     *
     * @return the value of SYS_ROLE.BRANCH_ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.BRANCH_ID
     *
     * @param branchId the value for SYS_ROLE.BRANCH_ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
}