package com.comstar.mars.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SecurityCouponScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public SecurityCouponScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSecurityCodeIsNull() {
            addCriterion("SECURITY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIsNotNull() {
            addCriterion("SECURITY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeEqualTo(String value) {
            addCriterion("SECURITY_CODE =", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotEqualTo(String value) {
            addCriterion("SECURITY_CODE <>", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeGreaterThan(String value) {
            addCriterion("SECURITY_CODE >", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SECURITY_CODE >=", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLessThan(String value) {
            addCriterion("SECURITY_CODE <", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLessThanOrEqualTo(String value) {
            addCriterion("SECURITY_CODE <=", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeLike(String value) {
            addCriterion("SECURITY_CODE like", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotLike(String value) {
            addCriterion("SECURITY_CODE not like", value, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeIn(List<String> values) {
            addCriterion("SECURITY_CODE in", values, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotIn(List<String> values) {
            addCriterion("SECURITY_CODE not in", values, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeBetween(String value1, String value2) {
            addCriterion("SECURITY_CODE between", value1, value2, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSecurityCodeNotBetween(String value1, String value2) {
            addCriterion("SECURITY_CODE not between", value1, value2, "securityCode");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("SEQ is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(Integer value) {
            addCriterion("SEQ =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(Integer value) {
            addCriterion("SEQ <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(Integer value) {
            addCriterion("SEQ >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(Integer value) {
            addCriterion("SEQ <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(Integer value) {
            addCriterion("SEQ <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<Integer> values) {
            addCriterion("SEQ in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<Integer> values) {
            addCriterion("SEQ not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(Integer value1, Integer value2) {
            addCriterion("SEQ between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andCusNumberIsNull() {
            addCriterion("CUS_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCusNumberIsNotNull() {
            addCriterion("CUS_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCusNumberEqualTo(Integer value) {
            addCriterion("CUS_NUMBER =", value, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberNotEqualTo(Integer value) {
            addCriterion("CUS_NUMBER <>", value, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberGreaterThan(Integer value) {
            addCriterion("CUS_NUMBER >", value, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUS_NUMBER >=", value, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberLessThan(Integer value) {
            addCriterion("CUS_NUMBER <", value, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberLessThanOrEqualTo(Integer value) {
            addCriterion("CUS_NUMBER <=", value, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberIn(List<Integer> values) {
            addCriterion("CUS_NUMBER in", values, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberNotIn(List<Integer> values) {
            addCriterion("CUS_NUMBER not in", values, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberBetween(Integer value1, Integer value2) {
            addCriterion("CUS_NUMBER between", value1, value2, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andCusNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CUS_NUMBER not between", value1, value2, "cusNumber");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(String value) {
            addCriterion("START_DATE =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(String value) {
            addCriterion("START_DATE <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(String value) {
            addCriterion("START_DATE >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("START_DATE >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(String value) {
            addCriterion("START_DATE <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(String value) {
            addCriterion("START_DATE <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLike(String value) {
            addCriterion("START_DATE like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotLike(String value) {
            addCriterion("START_DATE not like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<String> values) {
            addCriterion("START_DATE in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<String> values) {
            addCriterion("START_DATE not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(String value1, String value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(String value1, String value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("END_DATE like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("END_DATE not like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<String> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<String> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andCouponAmtIsNull() {
            addCriterion("COUPON_AMT is null");
            return (Criteria) this;
        }

        public Criteria andCouponAmtIsNotNull() {
            addCriterion("COUPON_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andCouponAmtEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMT =", value, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtNotEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMT <>", value, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtGreaterThan(BigDecimal value) {
            addCriterion("COUPON_AMT >", value, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMT >=", value, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtLessThan(BigDecimal value) {
            addCriterion("COUPON_AMT <", value, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COUPON_AMT <=", value, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtIn(List<BigDecimal> values) {
            addCriterion("COUPON_AMT in", values, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtNotIn(List<BigDecimal> values) {
            addCriterion("COUPON_AMT not in", values, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COUPON_AMT between", value1, value2, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andCouponAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COUPON_AMT not between", value1, value2, "couponAmt");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andInterestDaysIsNull() {
            addCriterion("INTEREST_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andInterestDaysIsNotNull() {
            addCriterion("INTEREST_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andInterestDaysEqualTo(BigDecimal value) {
            addCriterion("INTEREST_DAYS =", value, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysNotEqualTo(BigDecimal value) {
            addCriterion("INTEREST_DAYS <>", value, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysGreaterThan(BigDecimal value) {
            addCriterion("INTEREST_DAYS >", value, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST_DAYS >=", value, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysLessThan(BigDecimal value) {
            addCriterion("INTEREST_DAYS <", value, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST_DAYS <=", value, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysIn(List<BigDecimal> values) {
            addCriterion("INTEREST_DAYS in", values, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysNotIn(List<BigDecimal> values) {
            addCriterion("INTEREST_DAYS not in", values, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST_DAYS between", value1, value2, "interestDays");
            return (Criteria) this;
        }

        public Criteria andInterestDaysNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST_DAYS not between", value1, value2, "interestDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysIsNull() {
            addCriterion("YEAR_DAYS is null");
            return (Criteria) this;
        }

        public Criteria andYearDaysIsNotNull() {
            addCriterion("YEAR_DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andYearDaysEqualTo(BigDecimal value) {
            addCriterion("YEAR_DAYS =", value, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysNotEqualTo(BigDecimal value) {
            addCriterion("YEAR_DAYS <>", value, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysGreaterThan(BigDecimal value) {
            addCriterion("YEAR_DAYS >", value, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YEAR_DAYS >=", value, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysLessThan(BigDecimal value) {
            addCriterion("YEAR_DAYS <", value, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YEAR_DAYS <=", value, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysIn(List<BigDecimal> values) {
            addCriterion("YEAR_DAYS in", values, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysNotIn(List<BigDecimal> values) {
            addCriterion("YEAR_DAYS not in", values, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YEAR_DAYS between", value1, value2, "yearDays");
            return (Criteria) this;
        }

        public Criteria andYearDaysNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YEAR_DAYS not between", value1, value2, "yearDays");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 30 11:48:46 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}