package com.comstar.mars.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.NICK
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.SALT
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.BRANCH_ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private Integer branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.STATUS
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.ID
     *
     * @return the value of SYS_USER.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.ID
     *
     * @param id the value for SYS_USER.ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.NAME
     *
     * @return the value of SYS_USER.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.NAME
     *
     * @param name the value for SYS_USER.NAME
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.NICK
     *
     * @return the value of SYS_USER.NICK
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.NICK
     *
     * @param nick the value for SYS_USER.NICK
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PASSWORD
     *
     * @return the value of SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PASSWORD
     *
     * @param password the value for SYS_USER.PASSWORD
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.SALT
     *
     * @return the value of SYS_USER.SALT
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.SALT
     *
     * @param salt the value for SYS_USER.SALT
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.BRANCH_ID
     *
     * @return the value of SYS_USER.BRANCH_ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.BRANCH_ID
     *
     * @param branchId the value for SYS_USER.BRANCH_ID
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.STATUS
     *
     * @return the value of SYS_USER.STATUS
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.STATUS
     *
     * @param status the value for SYS_USER.STATUS
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}