package com.comstar.mars.repository;

import com.comstar.mars.entity.Branch;
import com.comstar.mars.entity.BranchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int countByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int deleteByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    List<Branch> selectByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    Branch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int updateByExampleSelective(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int updateByExample(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_BRANCH
     *
     * @mbggenerated Tue Aug 26 18:06:30 CST 2014
     */
    int updateByPrimaryKey(Branch record);
}