package com.comstar.mars.repository;

import com.comstar.mars.entity.DealSecurity;
import com.comstar.mars.entity.DealSecurityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealSecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int countByExample(DealSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int deleteByExample(DealSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int deleteByPrimaryKey(Long dealSecurityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int insert(DealSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int insertSelective(DealSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    List<DealSecurity> selectByExample(DealSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    DealSecurity selectByPrimaryKey(Long dealSecurityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") DealSecurity record, @Param("example") DealSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int updateByExample(@Param("record") DealSecurity record, @Param("example") DealSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int updateByPrimaryKeySelective(DealSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY
     *
     * @mbggenerated Thu Jul 10 13:48:35 CST 2014
     */
    int updateByPrimaryKey(DealSecurity record);
}