package com.comstar.mars.repository;

import com.comstar.mars.entity.DealSecurityActual;
import com.comstar.mars.entity.DealSecurityActualExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealSecurityActualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int countByExample(DealSecurityActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int deleteByExample(DealSecurityActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int deleteByPrimaryKey(Long dealSecurityActualId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int insert(DealSecurityActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int insertSelective(DealSecurityActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    List<DealSecurityActual> selectByExample(DealSecurityActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    DealSecurityActual selectByPrimaryKey(Long dealSecurityActualId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByExampleSelective(@Param("record") DealSecurityActual record, @Param("example") DealSecurityActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByExample(@Param("record") DealSecurityActual record, @Param("example") DealSecurityActualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByPrimaryKeySelective(DealSecurityActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACTUAL
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByPrimaryKey(DealSecurityActual record);
}