package com.comstar.mars.repository;

import com.comstar.mars.entity.DealSecurityAccrue;
import com.comstar.mars.entity.DealSecurityAccrueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealSecurityAccrueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int countByExample(DealSecurityAccrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int deleteByExample(DealSecurityAccrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int deleteByPrimaryKey(Long dealSecurityAccrueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int insert(DealSecurityAccrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int insertSelective(DealSecurityAccrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    List<DealSecurityAccrue> selectByExample(DealSecurityAccrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    DealSecurityAccrue selectByPrimaryKey(Long dealSecurityAccrueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int updateByExampleSelective(@Param("record") DealSecurityAccrue record, @Param("example") DealSecurityAccrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int updateByExample(@Param("record") DealSecurityAccrue record, @Param("example") DealSecurityAccrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int updateByPrimaryKeySelective(DealSecurityAccrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_ACCRUE
     *
     * @mbggenerated Thu Jul 10 14:33:03 CST 2014
     */
    int updateByPrimaryKey(DealSecurityAccrue record);
}