package com.comstar.mars.repository;

import com.comstar.mars.entity.DealSecurityReceivable;
import com.comstar.mars.entity.DealSecurityReceivableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealSecurityReceivableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int countByExample(DealSecurityReceivableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int deleteByExample(DealSecurityReceivableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int deleteByPrimaryKey(Long dealSecurityReceivableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int insert(DealSecurityReceivable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int insertSelective(DealSecurityReceivable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    List<DealSecurityReceivable> selectByExample(DealSecurityReceivableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    DealSecurityReceivable selectByPrimaryKey(Long dealSecurityReceivableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByExampleSelective(@Param("record") DealSecurityReceivable record, @Param("example") DealSecurityReceivableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByExample(@Param("record") DealSecurityReceivable record, @Param("example") DealSecurityReceivableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByPrimaryKeySelective(DealSecurityReceivable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEAL_SECURITY_RECEIVABLE
     *
     * @mbggenerated Thu Jul 10 14:16:03 CST 2014
     */
    int updateByPrimaryKey(DealSecurityReceivable record);
}