package com.comstar.mars.repository;

import com.comstar.mars.entity.FinancialProductCashflow;
import com.comstar.mars.entity.FinancialProductCashflowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinancialProductCashflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int countByExample(FinancialProductCashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int deleteByExample(FinancialProductCashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int deleteByPrimaryKey(Long financialProductCashflowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int insert(FinancialProductCashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int insertSelective(FinancialProductCashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    List<FinancialProductCashflow> selectByExample(FinancialProductCashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    FinancialProductCashflow selectByPrimaryKey(Long financialProductCashflowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") FinancialProductCashflow record, @Param("example") FinancialProductCashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int updateByExample(@Param("record") FinancialProductCashflow record, @Param("example") FinancialProductCashflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int updateByPrimaryKeySelective(FinancialProductCashflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT_CASHFLOW
     *
     * @mbggenerated Thu Jul 10 14:17:56 CST 2014
     */
    int updateByPrimaryKey(FinancialProductCashflow record);
}