package com.comstar.mars.repository;

import com.comstar.mars.entity.FinancialProduct;
import com.comstar.mars.entity.FinancialProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinancialProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int countByExample(FinancialProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int deleteByExample(FinancialProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int deleteByPrimaryKey(Integer financialProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int insert(FinancialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int insertSelective(FinancialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    List<FinancialProduct> selectByExample(FinancialProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    FinancialProduct selectByPrimaryKey(Integer financialProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int updateByExampleSelective(@Param("record") FinancialProduct record, @Param("example") FinancialProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int updateByExample(@Param("record") FinancialProduct record, @Param("example") FinancialProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int updateByPrimaryKeySelective(FinancialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FINANCIAL_PRODUCT
     *
     * @mbggenerated Thu Jul 10 14:33:02 CST 2014
     */
    int updateByPrimaryKey(FinancialProduct record);
}