package com.comstar.mars.repository;

import com.comstar.mars.entity.Privilege;
import com.comstar.mars.entity.PrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    Privilege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int updateByExample(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PRIVILEGE
     *
     * @mbggenerated Mon Sep 22 10:02:18 CST 2014
     */
    int updateByPrimaryKey(Privilege record);
}