package com.comstar.mars.repository;

import com.comstar.mars.entity.RolePrivilege;
import com.comstar.mars.entity.RolePrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int countByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int deleteByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int insert(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int insertSelective(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    List<RolePrivilege> selectByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int updateByExampleSelective(@Param("record") RolePrivilege record, @Param("example") RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_PRIVILEGE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int updateByExample(@Param("record") RolePrivilege record, @Param("example") RolePrivilegeExample example);
}