package com.comstar.mars.repository;

import com.comstar.mars.entity.Security;
import com.comstar.mars.entity.SecurityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int countByExample(SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int deleteByExample(SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int deleteByPrimaryKey(String securityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int insert(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int insertSelective(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    List<Security> selectByExample(SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    Security selectByPrimaryKey(String securityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int updateByExampleSelective(@Param("record") Security record, @Param("example") SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int updateByExample(@Param("record") Security record, @Param("example") SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int updateByPrimaryKeySelective(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY
     *
     * @mbggenerated Wed Jul 30 13:56:40 CST 2014
     */
    int updateByPrimaryKey(Security record);
}