package com.comstar.mars.repository;

import com.comstar.mars.entity.SecurityCouponSchedule;
import com.comstar.mars.entity.SecurityCouponScheduleExample;
import com.comstar.mars.entity.SecurityCouponScheduleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityCouponScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int countByExample(SecurityCouponScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int deleteByExample(SecurityCouponScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int deleteByPrimaryKey(SecurityCouponScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int insert(SecurityCouponSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int insertSelective(SecurityCouponSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    List<SecurityCouponSchedule> selectByExample(SecurityCouponScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    SecurityCouponSchedule selectByPrimaryKey(SecurityCouponScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int updateByExampleSelective(@Param("record") SecurityCouponSchedule record, @Param("example") SecurityCouponScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int updateByExample(@Param("record") SecurityCouponSchedule record, @Param("example") SecurityCouponScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int updateByPrimaryKeySelective(SecurityCouponSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMSTPLC.SECURITY_COUPON_SCHD
     *
     * @mbggenerated Wed Jul 30 11:48:46 CST 2014
     */
    int updateByPrimaryKey(SecurityCouponSchedule record);
}