package com.comstar.mars.repository;

import com.comstar.mars.entity.UserRole;
import com.comstar.mars.entity.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER_ROLE
     *
     * @mbggenerated Tue Aug 26 11:59:31 CST 2014
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);
}